-- MySQL Script generated by MySQL Workbench
-- Thu May 25 14:32:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema book_hunter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book_hunter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_hunter` DEFAULT CHARACTER SET utf8 ;
USE `book_hunter` ;

-- -----------------------------------------------------
-- Table `book_hunter`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`authors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `biography` TEXT NULL,
  `picture` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_hunter`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`categories` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_hunter`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`books` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(20) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `resume` TEXT NULL,
  `cover` VARCHAR(45) NULL,
  `publicated_at` DATE NULL,
  `created_at` DATETIME NOT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC),
  INDEX `fk_books_authors_idx` (`author_id` ASC),
  INDEX `fk_books_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_books_authors`
    FOREIGN KEY (`author_id`)
    REFERENCES `book_hunter`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `book_hunter`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_hunter`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`tags` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_hunter`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_hunter`.`books_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`books_has_tags` (
  `book_id` INT UNSIGNED NOT NULL,
  `tag_id` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`book_id`, `tag_id`),
  INDEX `fk_books_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_books_has_tags_books1_idx` (`book_id` ASC),
  CONSTRAINT `fk_books_has_tags_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `book_hunter`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `book_hunter`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_hunter`.`users_collections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`users_collections` (
  `user_id` INT UNSIGNED NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_users_has_books_books1_idx` (`book_id` ASC),
  INDEX `fk_users_has_books_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_books_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `book_hunter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `book_hunter`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_hunter`.`users_notations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_hunter`.`users_notations` (
  `user_id` INT UNSIGNED NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `note` DECIMAL(3,1) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `book_id`),
  INDEX `fk_users_has_books_books2_idx` (`book_id` ASC),
  INDEX `fk_users_has_books_users2_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_books_users2`
    FOREIGN KEY (`user_id`)
    REFERENCES `book_hunter`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books2`
    FOREIGN KEY (`book_id`)
    REFERENCES `book_hunter`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
